package com.airshiplay.play.app.model;

import java.io.Serializable;

public class AppAppversion implements Serializable {
    /**
     * database column <code>app_appversion.id</code>
     */
    private Long id;

    /**
     * database column <code>app_appversion.app_id</code>
     */
    private Long appId;

    /**
     * database column <code>app_appversion.app_version</code>
     */
    private String appVersion;

    /**
     * database column <code>app_appversion.app_version_code</code>
     */
    private Integer appVersionCode;

    /**
     * app版本信息描述
     * <p> 
     * database column <code>app_appversion.app_desc</code>
     */
    private String appDesc;

    /**
     * 版本平台
     * <p> 
     * database column <code>app_appversion.app_plat</code>
     */
    private String appPlat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_appversion
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return app_id
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * @param appId
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * @return app_version
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * @param appVersion
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * @return app_version_code
     */
    public Integer getAppVersionCode() {
        return appVersionCode;
    }

    /**
     * @param appVersionCode
     */
    public void setAppVersionCode(Integer appVersionCode) {
        this.appVersionCode = appVersionCode;
    }

    /**
     * 获取app版本信息描述
     *
     * @return app_desc - app版本信息描述
     */
    public String getAppDesc() {
        return appDesc;
    }

    /**
     * 设置app版本信息描述
     *
     * @param appDesc app版本信息描述
     */
    public void setAppDesc(String appDesc) {
        this.appDesc = appDesc == null ? null : appDesc.trim();
    }

    /**
     * 获取版本平台
     *
     * @return app_plat - 版本平台
     */
    public String getAppPlat() {
        return appPlat;
    }

    /**
     * 设置版本平台
     *
     * @param appPlat 版本平台
     */
    public void setAppPlat(String appPlat) {
        this.appPlat = appPlat == null ? null : appPlat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppAppversion other = (AppAppversion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getAppVersion() == null ? other.getAppVersion() == null : this.getAppVersion().equals(other.getAppVersion()))
            && (this.getAppVersionCode() == null ? other.getAppVersionCode() == null : this.getAppVersionCode().equals(other.getAppVersionCode()))
            && (this.getAppDesc() == null ? other.getAppDesc() == null : this.getAppDesc().equals(other.getAppDesc()))
            && (this.getAppPlat() == null ? other.getAppPlat() == null : this.getAppPlat().equals(other.getAppPlat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getAppVersion() == null) ? 0 : getAppVersion().hashCode());
        result = prime * result + ((getAppVersionCode() == null) ? 0 : getAppVersionCode().hashCode());
        result = prime * result + ((getAppDesc() == null) ? 0 : getAppDesc().hashCode());
        result = prime * result + ((getAppPlat() == null) ? 0 : getAppPlat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", appVersion=").append(appVersion);
        sb.append(", appVersionCode=").append(appVersionCode);
        sb.append(", appDesc=").append(appDesc);
        sb.append(", appPlat=").append(appPlat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}