package com.airshiplay.play.app.model;

import java.io.Serializable;

public class CoreOrgRole implements Serializable {
    /**
     * database column <code>core_org_role.id</code>
     */
    private Long id;

    /**
     * 角色编号
     * <p> 
     * database column <code>core_org_role.org_id</code>
     */
    private Long orgId;

    /**
     * 角色编号
     * <p> 
     * database column <code>core_org_role.role_id</code>
     */
    private Long roleId;

    /**
     * 组织机构角色信息描述
     * <p> 
     * database column <code>core_org_role.org_role_desc</code>
     */
    private String orgRoleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_org_role
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取角色编号
     *
     * @return org_id - 角色编号
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 设置角色编号
     *
     * @param orgId 角色编号
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取角色编号
     *
     * @return role_id - 角色编号
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * 设置角色编号
     *
     * @param roleId 角色编号
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取组织机构角色信息描述
     *
     * @return org_role_desc - 组织机构角色信息描述
     */
    public String getOrgRoleDesc() {
        return orgRoleDesc;
    }

    /**
     * 设置组织机构角色信息描述
     *
     * @param orgRoleDesc 组织机构角色信息描述
     */
    public void setOrgRoleDesc(String orgRoleDesc) {
        this.orgRoleDesc = orgRoleDesc == null ? null : orgRoleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreOrgRole other = (CoreOrgRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getOrgRoleDesc() == null ? other.getOrgRoleDesc() == null : this.getOrgRoleDesc().equals(other.getOrgRoleDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getOrgRoleDesc() == null) ? 0 : getOrgRoleDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orgId=").append(orgId);
        sb.append(", roleId=").append(roleId);
        sb.append(", orgRoleDesc=").append(orgRoleDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}