package com.airshiplay.play.app.model;

import java.io.Serializable;

public class CoreRolePermission implements Serializable {
    /**
     * database column <code>core_role_permission.id</code>
     */
    private Long id;

    /**
     * 角色编号
     * <p> 
     * database column <code>core_role_permission.role_id</code>
     */
    private Long roleId;

    /**
     * 权限编号
     * <p> 
     * database column <code>core_role_permission.permission_id</code>
     */
    private Long permissionId;

    /**
     * 角色权限信息描述
     * <p> 
     * database column <code>core_role_permission.role_permission_desc</code>
     */
    private String rolePermissionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_role_permission
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取角色编号
     *
     * @return role_id - 角色编号
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * 设置角色编号
     *
     * @param roleId 角色编号
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取权限编号
     *
     * @return permission_id - 权限编号
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * 设置权限编号
     *
     * @param permissionId 权限编号
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * 获取角色权限信息描述
     *
     * @return role_permission_desc - 角色权限信息描述
     */
    public String getRolePermissionDesc() {
        return rolePermissionDesc;
    }

    /**
     * 设置角色权限信息描述
     *
     * @param rolePermissionDesc 角色权限信息描述
     */
    public void setRolePermissionDesc(String rolePermissionDesc) {
        this.rolePermissionDesc = rolePermissionDesc == null ? null : rolePermissionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreRolePermission other = (CoreRolePermission) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()))
            && (this.getRolePermissionDesc() == null ? other.getRolePermissionDesc() == null : this.getRolePermissionDesc().equals(other.getRolePermissionDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        result = prime * result + ((getRolePermissionDesc() == null) ? 0 : getRolePermissionDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", rolePermissionDesc=").append(rolePermissionDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}