package com.airshiplay.play.app.model;

import java.io.Serializable;

public class CoreArea implements Serializable {
    /**
     * database column <code>core_area.id</code>
     */
    private Long id;

    /**
     * 名称（省、市、街道、小区 ）
     * <p> 
     * database column <code>core_area.area_name</code>
     */
    private String areaName;

    /**
     * 行政等级（1省、2市、3区）
     * <p> 
     * database column <code>core_area.area_level</code>
     */
    private Integer areaLevel;

    /**
     * 行政上级ID

     * <p> 
     * database column <code>core_area.upid</code>
     */
    private Long upid;

    /**
     * 显示顺序
     * <p> 
     * database column <code>core_area.display_order</code>
     */
    private Integer displayOrder;

    /**
     * database column <code>core_area.full_name</code>
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_area
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取名称（省、市、街道、小区 ）
     *
     * @return area_name - 名称（省、市、街道、小区 ）
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * 设置名称（省、市、街道、小区 ）
     *
     * @param areaName 名称（省、市、街道、小区 ）
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * 获取行政等级（1省、2市、3区）
     *
     * @return area_level - 行政等级（1省、2市、3区）
     */
    public Integer getAreaLevel() {
        return areaLevel;
    }

    /**
     * 设置行政等级（1省、2市、3区）
     *
     * @param areaLevel 行政等级（1省、2市、3区）
     */
    public void setAreaLevel(Integer areaLevel) {
        this.areaLevel = areaLevel;
    }

    /**
     * 获取行政上级ID

     *
     * @return upid - 行政上级ID

     */
    public Long getUpid() {
        return upid;
    }

    /**
     * 设置行政上级ID

     *
     * @param upid 行政上级ID

     */
    public void setUpid(Long upid) {
        this.upid = upid;
    }

    /**
     * 获取显示顺序
     *
     * @return display_order - 显示顺序
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * 设置显示顺序
     *
     * @param displayOrder 显示顺序
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * @return full_name
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * @param fullName
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreArea other = (CoreArea) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAreaName() == null ? other.getAreaName() == null : this.getAreaName().equals(other.getAreaName()))
            && (this.getAreaLevel() == null ? other.getAreaLevel() == null : this.getAreaLevel().equals(other.getAreaLevel()))
            && (this.getUpid() == null ? other.getUpid() == null : this.getUpid().equals(other.getUpid()))
            && (this.getDisplayOrder() == null ? other.getDisplayOrder() == null : this.getDisplayOrder().equals(other.getDisplayOrder()))
            && (this.getFullName() == null ? other.getFullName() == null : this.getFullName().equals(other.getFullName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAreaName() == null) ? 0 : getAreaName().hashCode());
        result = prime * result + ((getAreaLevel() == null) ? 0 : getAreaLevel().hashCode());
        result = prime * result + ((getUpid() == null) ? 0 : getUpid().hashCode());
        result = prime * result + ((getDisplayOrder() == null) ? 0 : getDisplayOrder().hashCode());
        result = prime * result + ((getFullName() == null) ? 0 : getFullName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", areaName=").append(areaName);
        sb.append(", areaLevel=").append(areaLevel);
        sb.append(", upid=").append(upid);
        sb.append(", displayOrder=").append(displayOrder);
        sb.append(", fullName=").append(fullName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}