package com.airshiplay.play.app.model;

import java.io.Serializable;

public class CoreUserGroup implements Serializable {
    /**
     * database column <code>core_user_group.id</code>
     */
    private Long id;

    /**
     * database column <code>core_user_group.user_id</code>
     */
    private Long userId;

    /**
     * database column <code>core_user_group.group_id</code>
     */
    private Long groupId;

    /**
     * 用户分组信息描述
     * <p> 
     * database column <code>core_user_group.user_group_desc</code>
     */
    private String userGroupDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_user_group
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return user_id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return group_id
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * @param groupId
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * 获取用户分组信息描述
     *
     * @return user_group_desc - 用户分组信息描述
     */
    public String getUserGroupDesc() {
        return userGroupDesc;
    }

    /**
     * 设置用户分组信息描述
     *
     * @param userGroupDesc 用户分组信息描述
     */
    public void setUserGroupDesc(String userGroupDesc) {
        this.userGroupDesc = userGroupDesc == null ? null : userGroupDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_group
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreUserGroup other = (CoreUserGroup) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getUserGroupDesc() == null ? other.getUserGroupDesc() == null : this.getUserGroupDesc().equals(other.getUserGroupDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_group
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getUserGroupDesc() == null) ? 0 : getUserGroupDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_group
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", groupId=").append(groupId);
        sb.append(", userGroupDesc=").append(userGroupDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}