package com.airshiplay.play.app.model;

import java.io.Serializable;

public class CoreUserOrg implements Serializable {
    /**
     * database column <code>core_user_org.id</code>
     */
    private Long id;

    /**
     * database column <code>core_user_org.user_id</code>
     */
    private Long userId;

    /**
     * 组织机构ID
     * <p> 
     * database column <code>core_user_org.org_id</code>
     */
    private Long orgId;

    /**
     * 用户组织结构信息描述
     * <p> 
     * database column <code>core_user_org.user_org_desc</code>
     */
    private String userOrgDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_user_org
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return user_id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 获取组织机构ID
     *
     * @return org_id - 组织机构ID
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 设置组织机构ID
     *
     * @param orgId 组织机构ID
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取用户组织结构信息描述
     *
     * @return user_org_desc - 用户组织结构信息描述
     */
    public String getUserOrgDesc() {
        return userOrgDesc;
    }

    /**
     * 设置用户组织结构信息描述
     *
     * @param userOrgDesc 用户组织结构信息描述
     */
    public void setUserOrgDesc(String userOrgDesc) {
        this.userOrgDesc = userOrgDesc == null ? null : userOrgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_org
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreUserOrg other = (CoreUserOrg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getUserOrgDesc() == null ? other.getUserOrgDesc() == null : this.getUserOrgDesc().equals(other.getUserOrgDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_org
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getUserOrgDesc() == null) ? 0 : getUserOrgDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_org
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orgId=").append(orgId);
        sb.append(", userOrgDesc=").append(userOrgDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}