package com.airshiplay.play.app.model;

import java.io.Serializable;

public class CoreRole implements Serializable {
    /**
     * database column <code>core_role.id</code>
     */
    private Long id;

    /**
     * 角色名称
     * <p> 
     * database column <code>core_role.role_name</code>
     */
    private String roleName;

    /**
     * 角色信息描述
     * <p> 
     * database column <code>core_role.role_desc</code>
     */
    private String roleDesc;

    /**
     * 角色类型：0通用用户角色；1、组织机构角色；2、用户组角色
     * <p> 
     * database column <code>core_role.role_type</code>
     */
    private Integer roleType;

    /**
     * 角色编码
     * <p> 
     * database column <code>core_role.role_code</code>
     */
    private String roleCode;

    /**
     * 是否可以编辑，修改
     * <p> 
     * database column <code>core_role.edit</code>
     */
    private String edit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_role
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取角色名称
     *
     * @return role_name - 角色名称
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * 设置角色名称
     *
     * @param roleName 角色名称
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * 获取角色信息描述
     *
     * @return role_desc - 角色信息描述
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * 设置角色信息描述
     *
     * @param roleDesc 角色信息描述
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * 获取角色类型：0通用用户角色；1、组织机构角色；2、用户组角色
     *
     * @return role_type - 角色类型：0通用用户角色；1、组织机构角色；2、用户组角色
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * 设置角色类型：0通用用户角色；1、组织机构角色；2、用户组角色
     *
     * @param roleType 角色类型：0通用用户角色；1、组织机构角色；2、用户组角色
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * 获取角色编码
     *
     * @return role_code - 角色编码
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * 设置角色编码
     *
     * @param roleCode 角色编码
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * 获取是否可以编辑，修改
     *
     * @return edit - 是否可以编辑，修改
     */
    public String getEdit() {
        return edit;
    }

    /**
     * 设置是否可以编辑，修改
     *
     * @param edit 是否可以编辑，修改
     */
    public void setEdit(String edit) {
        this.edit = edit == null ? null : edit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreRole other = (CoreRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getRoleDesc() == null ? other.getRoleDesc() == null : this.getRoleDesc().equals(other.getRoleDesc()))
            && (this.getRoleType() == null ? other.getRoleType() == null : this.getRoleType().equals(other.getRoleType()))
            && (this.getRoleCode() == null ? other.getRoleCode() == null : this.getRoleCode().equals(other.getRoleCode()))
            && (this.getEdit() == null ? other.getEdit() == null : this.getEdit().equals(other.getEdit()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getRoleDesc() == null) ? 0 : getRoleDesc().hashCode());
        result = prime * result + ((getRoleType() == null) ? 0 : getRoleType().hashCode());
        result = prime * result + ((getRoleCode() == null) ? 0 : getRoleCode().hashCode());
        result = prime * result + ((getEdit() == null) ? 0 : getEdit().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleDesc=").append(roleDesc);
        sb.append(", roleType=").append(roleType);
        sb.append(", roleCode=").append(roleCode);
        sb.append(", edit=").append(edit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}