package com.airshiplay.play.app.model;

import java.io.Serializable;

public class CoreGroupRole implements Serializable {
    /**
     * database column <code>core_group_role.id</code>
     */
    private Long id;

    /**
     * 角色编号
     * <p> 
     * database column <code>core_group_role.group_id</code>
     */
    private Long groupId;

    /**
     * 角色编号
     * <p> 
     * database column <code>core_group_role.role_id</code>
     */
    private Long roleId;

    /**
     * 分组角色信息描述
     * <p> 
     * database column <code>core_group_role.group_role_desc</code>
     */
    private String groupRoleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_group_role
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取角色编号
     *
     * @return group_id - 角色编号
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * 设置角色编号
     *
     * @param groupId 角色编号
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * 获取角色编号
     *
     * @return role_id - 角色编号
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * 设置角色编号
     *
     * @param roleId 角色编号
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取分组角色信息描述
     *
     * @return group_role_desc - 分组角色信息描述
     */
    public String getGroupRoleDesc() {
        return groupRoleDesc;
    }

    /**
     * 设置分组角色信息描述
     *
     * @param groupRoleDesc 分组角色信息描述
     */
    public void setGroupRoleDesc(String groupRoleDesc) {
        this.groupRoleDesc = groupRoleDesc == null ? null : groupRoleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreGroupRole other = (CoreGroupRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getGroupRoleDesc() == null ? other.getGroupRoleDesc() == null : this.getGroupRoleDesc().equals(other.getGroupRoleDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getGroupRoleDesc() == null) ? 0 : getGroupRoleDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", roleId=").append(roleId);
        sb.append(", groupRoleDesc=").append(groupRoleDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}