package com.airshiplay.play.app.model;

import java.io.Serializable;

public class CoreUserRole implements Serializable {
    /**
     * database column <code>core_user_role.id</code>
     */
    private Long id;

    /**
     * database column <code>core_user_role.user_id</code>
     */
    private Long userId;

    /**
     * database column <code>core_user_role.role_id</code>
     */
    private Long roleId;

    /**
     * 用户角色信息描述
     * <p> 
     * database column <code>core_user_role.user_role_desc</code>
     */
    private String userRoleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_user_role
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return user_id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return role_id
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * @param roleId
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取用户角色信息描述
     *
     * @return user_role_desc - 用户角色信息描述
     */
    public String getUserRoleDesc() {
        return userRoleDesc;
    }

    /**
     * 设置用户角色信息描述
     *
     * @param userRoleDesc 用户角色信息描述
     */
    public void setUserRoleDesc(String userRoleDesc) {
        this.userRoleDesc = userRoleDesc == null ? null : userRoleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_role
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoreUserRole other = (CoreUserRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getUserRoleDesc() == null ? other.getUserRoleDesc() == null : this.getUserRoleDesc().equals(other.getUserRoleDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_role
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getUserRoleDesc() == null) ? 0 : getUserRoleDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user_role
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", userRoleDesc=").append(userRoleDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}