package com.airshiplay.play.app.model;

import java.io.Serializable;

public class OfCatalog implements Serializable {
    /**
     * 主键自增长
     * <p> 
     * database column <code>of_catalog.id</code>
     */
    private Long id;

    /**
     * database column <code>of_catalog.catalog_name</code>
     */
    private String catalogName;

    /**
     * database column <code>of_catalog.remark</code>
     */
    private String remark;

    /**
     * 栏目显示顺序
     * <p> 
     * database column <code>of_catalog.seq</code>
     */
    private Integer seq;

    /**
     * 栏目状态
     * <p> 
     * database column <code>of_catalog.status</code>
     */
    private Integer status;

    /**
     * 上级栏目ID
     * <p> 
     * database column <code>of_catalog.upid</code>
     */
    private Long upid;

    /**
     * 栏目类型-detail页面-list列表页面
     * <p> 
     * database column <code>of_catalog.type</code>
     */
    private String type;

    /**
     * 层次等级
     * <p> 
     * database column <code>of_catalog.level</code>
     */
    private Integer level;

    /**
     * url访问路径
     * <p> 
     * database column <code>of_catalog.url_path</code>
     */
    private String urlPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table of_catalog
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取主键自增长
     *
     * @return id - 主键自增长
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置主键自增长
     *
     * @param id 主键自增长
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return catalog_name
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * @param catalogName
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName == null ? null : catalogName.trim();
    }

    /**
     * @return remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取栏目显示顺序
     *
     * @return seq - 栏目显示顺序
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * 设置栏目显示顺序
     *
     * @param seq 栏目显示顺序
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * 获取栏目状态
     *
     * @return status - 栏目状态
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置栏目状态
     *
     * @param status 栏目状态
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取上级栏目ID
     *
     * @return upid - 上级栏目ID
     */
    public Long getUpid() {
        return upid;
    }

    /**
     * 设置上级栏目ID
     *
     * @param upid 上级栏目ID
     */
    public void setUpid(Long upid) {
        this.upid = upid;
    }

    /**
     * 获取栏目类型-detail页面-list列表页面
     *
     * @return type - 栏目类型-detail页面-list列表页面
     */
    public String getType() {
        return type;
    }

    /**
     * 设置栏目类型-detail页面-list列表页面
     *
     * @param type 栏目类型-detail页面-list列表页面
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 获取层次等级
     *
     * @return level - 层次等级
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * 设置层次等级
     *
     * @param level 层次等级
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * 获取url访问路径
     *
     * @return url_path - url访问路径
     */
    public String getUrlPath() {
        return urlPath;
    }

    /**
     * 设置url访问路径
     *
     * @param urlPath url访问路径
     */
    public void setUrlPath(String urlPath) {
        this.urlPath = urlPath == null ? null : urlPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OfCatalog other = (OfCatalog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCatalogName() == null ? other.getCatalogName() == null : this.getCatalogName().equals(other.getCatalogName()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getSeq() == null ? other.getSeq() == null : this.getSeq().equals(other.getSeq()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUpid() == null ? other.getUpid() == null : this.getUpid().equals(other.getUpid()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getUrlPath() == null ? other.getUrlPath() == null : this.getUrlPath().equals(other.getUrlPath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCatalogName() == null) ? 0 : getCatalogName().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUpid() == null) ? 0 : getUpid().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getUrlPath() == null) ? 0 : getUrlPath().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", catalogName=").append(catalogName);
        sb.append(", remark=").append(remark);
        sb.append(", seq=").append(seq);
        sb.append(", status=").append(status);
        sb.append(", upid=").append(upid);
        sb.append(", type=").append(type);
        sb.append(", level=").append(level);
        sb.append(", urlPath=").append(urlPath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}