package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.ObdActivityObd4storeExample;
import com.airshiplay.play.app.model.ObdActivityObd4storeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObdActivityObd4storeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    long countByExample(ObdActivityObd4storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    int deleteByExample(ObdActivityObd4storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    int deleteByPrimaryKey(ObdActivityObd4storeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    int insert(ObdActivityObd4storeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    int insertSelective(ObdActivityObd4storeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    List<ObdActivityObd4storeKey> selectByExample(ObdActivityObd4storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ObdActivityObd4storeKey record, @Param("example") ObdActivityObd4storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    int updateByExample(@Param("record") ObdActivityObd4storeKey record, @Param("example") ObdActivityObd4storeExample example);
}