package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.ObdActivity;
import com.airshiplay.play.app.model.ObdActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObdActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    long countByExample(ObdActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    int deleteByExample(ObdActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    int insert(ObdActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    int insertSelective(ObdActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    List<ObdActivity> selectByExample(ObdActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    ObdActivity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ObdActivity record, @Param("example") ObdActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    int updateByExample(@Param("record") ObdActivity record, @Param("example") ObdActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    int updateByPrimaryKeySelective(ObdActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity
     *
     * @date
     */
    int updateByPrimaryKey(ObdActivity record);
}