package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.ObdCar;
import com.airshiplay.play.app.model.ObdCarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObdCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    long countByExample(ObdCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    int deleteByExample(ObdCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    int insert(ObdCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    int insertSelective(ObdCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    List<ObdCar> selectByExample(ObdCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    ObdCar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ObdCar record, @Param("example") ObdCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    int updateByExample(@Param("record") ObdCar record, @Param("example") ObdCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    int updateByPrimaryKeySelective(ObdCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_car
     *
     * @date
     */
    int updateByPrimaryKey(ObdCar record);
}