package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.ObdDevice;
import com.airshiplay.play.app.model.ObdDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObdDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    long countByExample(ObdDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    int deleteByExample(ObdDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    int insert(ObdDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    int insertSelective(ObdDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    List<ObdDevice> selectByExample(ObdDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    ObdDevice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ObdDevice record, @Param("example") ObdDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    int updateByExample(@Param("record") ObdDevice record, @Param("example") ObdDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    int updateByPrimaryKeySelective(ObdDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_device
     *
     * @date
     */
    int updateByPrimaryKey(ObdDevice record);
}