package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.ObdMemberRank;
import com.airshiplay.play.app.model.ObdMemberRankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObdMemberRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    long countByExample(ObdMemberRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    int deleteByExample(ObdMemberRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    int insert(ObdMemberRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    int insertSelective(ObdMemberRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    List<ObdMemberRank> selectByExample(ObdMemberRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    ObdMemberRank selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ObdMemberRank record, @Param("example") ObdMemberRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    int updateByExample(@Param("record") ObdMemberRank record, @Param("example") ObdMemberRankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    int updateByPrimaryKeySelective(ObdMemberRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_member_rank
     *
     * @date
     */
    int updateByPrimaryKey(ObdMemberRank record);
}