package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.ObdStore4sService;
import com.airshiplay.play.app.model.ObdStore4sServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObdStore4sServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    long countByExample(ObdStore4sServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    int deleteByExample(ObdStore4sServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    int insert(ObdStore4sService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    int insertSelective(ObdStore4sService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    List<ObdStore4sService> selectByExample(ObdStore4sServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    ObdStore4sService selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ObdStore4sService record, @Param("example") ObdStore4sServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    int updateByExample(@Param("record") ObdStore4sService record, @Param("example") ObdStore4sServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    int updateByPrimaryKeySelective(ObdStore4sService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_store4s_service
     *
     * @date
     */
    int updateByPrimaryKey(ObdStore4sService record);
}