package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.ObdVehicleAlarm;
import com.airshiplay.play.app.model.ObdVehicleAlarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObdVehicleAlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    long countByExample(ObdVehicleAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    int deleteByExample(ObdVehicleAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    int insert(ObdVehicleAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    int insertSelective(ObdVehicleAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    List<ObdVehicleAlarm> selectByExample(ObdVehicleAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    ObdVehicleAlarm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ObdVehicleAlarm record, @Param("example") ObdVehicleAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    int updateByExample(@Param("record") ObdVehicleAlarm record, @Param("example") ObdVehicleAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    int updateByPrimaryKeySelective(ObdVehicleAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle_alarm
     *
     * @date
     */
    int updateByPrimaryKey(ObdVehicleAlarm record);
}