package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.ObdVehicle;
import com.airshiplay.play.app.model.ObdVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObdVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    long countByExample(ObdVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    int deleteByExample(ObdVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    int insert(ObdVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    int insertSelective(ObdVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    List<ObdVehicle> selectByExample(ObdVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    ObdVehicle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ObdVehicle record, @Param("example") ObdVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    int updateByExample(@Param("record") ObdVehicle record, @Param("example") ObdVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    int updateByPrimaryKeySelective(ObdVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_vehicle
     *
     * @date
     */
    int updateByPrimaryKey(ObdVehicle record);
}