server:
  port: 18080
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18888/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: play-admin-provider
  datasource:
      url : jdbc:h2:mem:example
      username : sa
      password :
      driver-class-name : org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  profiles:
    active: dev
security:
  oauth2:
    resource:
      id: play-admin-provider
      user-info-uri: http://localhost:18080/admin/user
      prefer-token-info: false
      jwt:
        key-value: 123
#    client:
#      client-id: curl-client
#      client-secret: curl-secret
#      access-token-uri: http://localhost:18088/oauth/token
#      user-authorization-uri: http://localhost:18088/oauth/authorize
logging:
  level:
    org.springframework.security: DEBUG
