eureka:
  client:
    service-url:
      defaultZone: http://localhost:18888/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8082
spring:
  application:
    name: play-config-center-server
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/airshiplay/play-config-repo
          username: airshiplay@126.com
          password: 11
security:
  oauth2:
    resource:
      id: center-service
      user-info-uri: http://localhost:18088/user
      prefer-token-info: false
logging:
  level:
    org.springframework.security: DEBUG
#security:
#  oauth2:
#    client:
#      client-id: curl-client
#      client-secret: curl-secret
#      access-token-uri: http://localhost:18080/oauth/token
#      user-authorization-uri: http://localhost:18080/oauth/authorize
#    resource:
#      user-info-uri: http://localhost:18080/user
