package com.airshiplay.play.app.model;

import java.io.Serializable;

/**
 *
 * database table obd_activity_obd_4store
 *
 * @date do_not_delete_during_merge
 */
public class ObdActivityObd4storeKey implements Serializable {
    private Long activityEntity_id;

    private Long store4Ss_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getActivityEntity_id() {
        return activityEntity_id;
    }

    public void setActivityEntity_id(Long activityEntity_id) {
        this.activityEntity_id = activityEntity_id;
    }

    public Long getStore4Ss_id() {
        return store4Ss_id;
    }

    public void setStore4Ss_id(Long store4Ss_id) {
        this.store4Ss_id = store4Ss_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ObdActivityObd4storeKey other = (ObdActivityObd4storeKey) that;
        return (this.getActivityEntity_id() == null ? other.getActivityEntity_id() == null : this.getActivityEntity_id().equals(other.getActivityEntity_id()))
            && (this.getStore4Ss_id() == null ? other.getStore4Ss_id() == null : this.getStore4Ss_id().equals(other.getStore4Ss_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActivityEntity_id() == null) ? 0 : getActivityEntity_id().hashCode());
        result = prime * result + ((getStore4Ss_id() == null) ? 0 : getStore4Ss_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_activity_obd_4store
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", activityEntity_id=").append(activityEntity_id);
        sb.append(", store4Ss_id=").append(store4Ss_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}