package com.airshiplay.play.app.model;

import java.util.ArrayList;
import java.util.List;

public class ObdUserToOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obd_user_to_order
     *
     * @date
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obd_user_to_order
     *
     * @date
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obd_user_to_order
     *
     * @date
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public ObdUserToOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * 
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUsers_idIsNull() {
            addCriterion("users_id is null");
            return (Criteria) this;
        }

        public Criteria andUsers_idIsNotNull() {
            addCriterion("users_id is not null");
            return (Criteria) this;
        }

        public Criteria andUsers_idEqualTo(Long value) {
            addCriterion("users_id =", value, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idNotEqualTo(Long value) {
            addCriterion("users_id <>", value, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idGreaterThan(Long value) {
            addCriterion("users_id >", value, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idGreaterThanOrEqualTo(Long value) {
            addCriterion("users_id >=", value, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idLessThan(Long value) {
            addCriterion("users_id <", value, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idLessThanOrEqualTo(Long value) {
            addCriterion("users_id <=", value, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idIn(List<Long> values) {
            addCriterion("users_id in", values, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idNotIn(List<Long> values) {
            addCriterion("users_id not in", values, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idBetween(Long value1, Long value2) {
            addCriterion("users_id between", value1, value2, "users_id");
            return (Criteria) this;
        }

        public Criteria andUsers_idNotBetween(Long value1, Long value2) {
            addCriterion("users_id not between", value1, value2, "users_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idIsNull() {
            addCriterion("orders_id is null");
            return (Criteria) this;
        }

        public Criteria andOrders_idIsNotNull() {
            addCriterion("orders_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrders_idEqualTo(Long value) {
            addCriterion("orders_id =", value, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idNotEqualTo(Long value) {
            addCriterion("orders_id <>", value, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idGreaterThan(Long value) {
            addCriterion("orders_id >", value, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idGreaterThanOrEqualTo(Long value) {
            addCriterion("orders_id >=", value, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idLessThan(Long value) {
            addCriterion("orders_id <", value, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idLessThanOrEqualTo(Long value) {
            addCriterion("orders_id <=", value, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idIn(List<Long> values) {
            addCriterion("orders_id in", values, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idNotIn(List<Long> values) {
            addCriterion("orders_id not in", values, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idBetween(Long value1, Long value2) {
            addCriterion("orders_id between", value1, value2, "orders_id");
            return (Criteria) this;
        }

        public Criteria andOrders_idNotBetween(Long value1, Long value2) {
            addCriterion("orders_id not between", value1, value2, "orders_id");
            return (Criteria) this;
        }
    }

    /**
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}