package com.airshiplay.play.app.model;

import java.io.Serializable;

/**
 *
 * database table obd_user
 *
 * @date do_not_delete_during_merge
 */
public class ObdUser implements Serializable {
    private Long id;

    private Long obdrank_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obd_user
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getObdrank_id() {
        return obdrank_id;
    }

    public void setObdrank_id(Long obdrank_id) {
        this.obdrank_id = obdrank_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ObdUser other = (ObdUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getObdrank_id() == null ? other.getObdrank_id() == null : this.getObdrank_id().equals(other.getObdrank_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getObdrank_id() == null) ? 0 : getObdrank_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", obdrank_id=").append(obdrank_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}