package com.airshiplay.play.app.model;

import java.io.Serializable;

/**
 *
 * database table obd_user_to_order
 *
 * @date do_not_delete_during_merge
 */
public class ObdUserToOrderKey implements Serializable {
    private Long users_id;

    private Long orders_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obd_user_to_order
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getUsers_id() {
        return users_id;
    }

    public void setUsers_id(Long users_id) {
        this.users_id = users_id;
    }

    public Long getOrders_id() {
        return orders_id;
    }

    public void setOrders_id(Long orders_id) {
        this.orders_id = orders_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ObdUserToOrderKey other = (ObdUserToOrderKey) that;
        return (this.getUsers_id() == null ? other.getUsers_id() == null : this.getUsers_id().equals(other.getUsers_id()))
            && (this.getOrders_id() == null ? other.getOrders_id() == null : this.getOrders_id().equals(other.getOrders_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUsers_id() == null) ? 0 : getUsers_id().hashCode());
        result = prime * result + ((getOrders_id() == null) ? 0 : getOrders_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obd_user_to_order
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", users_id=").append(users_id);
        sb.append(", orders_id=").append(orders_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}