server:
  port: 18081
spring:
  cloud:
    gateway:
      routes:
      - id: adminapi
        uri: lb://play-admin-provider
        predicates:
        - Path=/admin/**
        filters:
        - StripPrefix=1
  application:
    name: play-gateway
eureka:
  client:
    service-url:
      defaultZone: http://172.19.201.251:18888/eureka
  instance:
    prefer-ip-address: true