spring:
  application:
    name: play-auth-center-provider
  datasource:
      url : jdbc:h2:mem:example
      username : sa
      password :
      driver-class-name : org.h2.Driver
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
server:
  port: 18088
  servlet:
    context-path: /auth
    session:
      cookie:
        name: PLAY-OAUTH-SESSION
logging:
  level:
    org.springframework.security: DEBUG
debug: true
feign:
  hystrix:
   enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18888/eureka
  instance:
    prefer-ip-address: true