package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.AppAppversion;
import com.airshiplay.play.app.model.AppAppversionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppAppversionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int countByExample(AppAppversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int deleteByExample(AppAppversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int insert(AppAppversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int insertSelective(AppAppversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    List<AppAppversion> selectByExample(AppAppversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    AppAppversion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppAppversion record, @Param("example") AppAppversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppAppversion record, @Param("example") AppAppversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppAppversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appversion
     * @mbggenerated
     */
    int updateByPrimaryKey(AppAppversion record);
}