package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.AppApplication;
import com.airshiplay.play.app.model.AppApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int countByExample(AppApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int deleteByExample(AppApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int insert(AppApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int insertSelective(AppApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    List<AppApplication> selectByExample(AppApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    AppApplication selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppApplication record, @Param("example") AppApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppApplication record, @Param("example") AppApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_application
     * @mbggenerated
     */
    int updateByPrimaryKey(AppApplication record);
}