package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreArea;
import com.airshiplay.play.app.model.CoreAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int countByExample(CoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int deleteByExample(CoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int insert(CoreArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int insertSelective(CoreArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    List<CoreArea> selectByExample(CoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    CoreArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreArea record, @Param("example") CoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreArea record, @Param("example") CoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_area
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreArea record);
}