package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreUsrLog;
import com.airshiplay.play.app.model.CoreUsrLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreUsrLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int countByExample(CoreUsrLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int deleteByExample(CoreUsrLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int insert(CoreUsrLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int insertSelective(CoreUsrLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    List<CoreUsrLog> selectByExample(CoreUsrLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    CoreUsrLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreUsrLog record, @Param("example") CoreUsrLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreUsrLog record, @Param("example") CoreUsrLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreUsrLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_log
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreUsrLog record);
}