package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreGroupRole;
import com.airshiplay.play.app.model.CoreGroupRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreGroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int countByExample(CoreGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int deleteByExample(CoreGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int insert(CoreGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int insertSelective(CoreGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    List<CoreGroupRole> selectByExample(CoreGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    CoreGroupRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreGroupRole record, @Param("example") CoreGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreGroupRole record, @Param("example") CoreGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group_role
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreGroupRole record);
}