package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreRolePermission;
import com.airshiplay.play.app.model.CoreRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int countByExample(CoreRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int deleteByExample(CoreRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int insert(CoreRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int insertSelective(CoreRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    List<CoreRolePermission> selectByExample(CoreRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    CoreRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreRolePermission record, @Param("example") CoreRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreRolePermission record, @Param("example") CoreRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role_permission
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreRolePermission record);
}