package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreUsrProfile;
import com.airshiplay.play.app.model.CoreUsrProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreUsrProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int countByExample(CoreUsrProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int deleteByExample(CoreUsrProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int insert(CoreUsrProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int insertSelective(CoreUsrProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    List<CoreUsrProfile> selectByExample(CoreUsrProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    CoreUsrProfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreUsrProfile record, @Param("example") CoreUsrProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreUsrProfile record, @Param("example") CoreUsrProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreUsrProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_usr_profile
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreUsrProfile record);
}