package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreGroup;
import com.airshiplay.play.app.model.CoreGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int countByExample(CoreGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int deleteByExample(CoreGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int insert(CoreGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int insertSelective(CoreGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    List<CoreGroup> selectByExample(CoreGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    CoreGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreGroup record, @Param("example") CoreGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreGroup record, @Param("example") CoreGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_group
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreGroup record);
}