package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CorePermission;
import com.airshiplay.play.app.model.CorePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CorePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int countByExample(CorePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int deleteByExample(CorePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int insert(CorePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int insertSelective(CorePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    List<CorePermission> selectByExample(CorePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    CorePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CorePermission record, @Param("example") CorePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int updateByExample(@Param("record") CorePermission record, @Param("example") CorePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CorePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_permission
     * @mbggenerated
     */
    int updateByPrimaryKey(CorePermission record);
}