package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreOrg;
import com.airshiplay.play.app.model.CoreOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int countByExample(CoreOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int deleteByExample(CoreOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int insert(CoreOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int insertSelective(CoreOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    List<CoreOrg> selectByExample(CoreOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    CoreOrg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreOrg record, @Param("example") CoreOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreOrg record, @Param("example") CoreOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreOrg record);
}