package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreOrgRole;
import com.airshiplay.play.app.model.CoreOrgRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreOrgRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int countByExample(CoreOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int deleteByExample(CoreOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int insert(CoreOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int insertSelective(CoreOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    List<CoreOrgRole> selectByExample(CoreOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    CoreOrgRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreOrgRole record, @Param("example") CoreOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreOrgRole record, @Param("example") CoreOrgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_org_role
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreOrgRole record);
}