package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.CoreRole;
import com.airshiplay.play.app.model.CoreRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int countByExample(CoreRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int deleteByExample(CoreRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int insert(CoreRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int insertSelective(CoreRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    List<CoreRole> selectByExample(CoreRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    CoreRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreRole record, @Param("example") CoreRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreRole record, @Param("example") CoreRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_role
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreRole record);
}