package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.OfCatalog;
import com.airshiplay.play.app.model.OfCatalogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfCatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int countByExample(OfCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int deleteByExample(OfCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int insert(OfCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int insertSelective(OfCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    List<OfCatalog> selectByExample(OfCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    OfCatalog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfCatalog record, @Param("example") OfCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfCatalog record, @Param("example") OfCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog
     * @mbggenerated
     */
    int updateByPrimaryKey(OfCatalog record);
}