package com.airshiplay.play.app.mapper;

import com.airshiplay.play.app.model.WxUser;
import com.airshiplay.play.app.model.WxUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int countByExample(WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int deleteByExample(WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int insert(WxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int insertSelective(WxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    List<WxUser> selectByExample(WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    WxUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxUser record, @Param("example") WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxUser record, @Param("example") WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     * @mbggenerated
     */
    int updateByPrimaryKey(WxUser record);
}